services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: pi_timescale
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - app_network

  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pi_next_app_prod
    ports:
      - '3000:3000'
    restart: always
    environment:
      NODE_ENV: production
    depends_on:
      - timescaledb
    networks:
      - app_network
    user: node 

networks:
  app_network:
    driver: bridge

volumes:
  timescaledb_data:
