[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  knolleary/PubSubClient@^2.8
  adafruit/Adafruit MPU6050 @ ^2.2.4
  adafruit/Adafruit Unified Sensor @ ^1.1.14
  adafruit/Adafruit BusIO @ ^1.16.0
  deneyapkart/Deneyap Servo@^1.1.1

build_flags = -DCORE_DEBUG_LEVEL=0